### PR TITLE
Directory tree created on startup

### LINKED ISSUE #179: Parent folder not created when writing nested file
If connecting empty repos to one that has nested files, the newcomers can crash:
If trying to write (include pull, redundancy) a file in a folder
-> Because the parent folder has not been created.

Crashes as soon as they join if redundancy is enabled.
Should crash when a file is requested otherwise

We should probably recursively create missing dirs, but I'm not sure where to do it.
In the DiskManagers could be nice and simple, but they don't have access to arbo and can't set right permissions
Otherwise we need to create a function every time we interact with the disk, but that's a lot of boilerplate

While this is not fixed, the only solution is to start every repo with the same base layout.

### PR DESCRIPTION
**Pull request by axel-denis**
fixes #179 
Creates the directory tree at startup (only directories, not files)

### CODE REVIEW

File: src/pods/pod.rs [hunk 1]
```diff
@@ -134,6 +137,66 @@ custom_error! {pub PodStopError
     FileNotSent{file: InodeId} = "PodStopError: no pod was able to receive this file before stopping: ({file})"
 }
 
+/// Create all the directories present in Arbo. (not the files)
+///
+/// Required at setup to resolve issue #179
+/// (files pulling need the parent folder to be already present)
+fn create_all_dirs(arbo: &Arbo, from: InodeId, mount_point: &WhPath) -> io::Result<()> {
+    let to_io_error = |_| {
```
Comment (Arthur-Aillet) [inline src/pods/pod.rs:145]: Creating an lambda like this at the start of root scope of the function, is very confusing, think embedding it is preferable

File: src/pods/pod.rs [hunk 2]
```diff
@@ -134,6 +137,66 @@ custom_error! {pub PodStopError
...
+
+    let current_path = arbo
+        .n_get_path_from_inode_id(from.id)
+        .map_err(to_io_error)?;
+    ignore_exists(fs::create_dir(&mount_point.join(&current_path)))?;
+
+    for (path, perms, children) in directories {
+        let path = mount_point.join(&path);
+        ignore_exists(fs::create_dir(&path))?;
+        // REVIEW permissions are just reconverted from u16 to u32, as I've seen them
```
Comment (Arthur-Aillet) [inline src/pods/pod.rs:188]: Seems correct, when you go from u32 to u16 you don't lose any permission information, you lose things like mode

File: src/pods/pod.rs (hunk 1 above)
Comment (Arthur-Aillet) [reply src/pods/pod.rs:145]: Just store an error and not a scope and it should be clearer

File: src/pods/pod.rs [hunk 3]
```diff
@@ -134,6 +137,66 @@ custom_error! {pub PodStopError
...
+/// Required at setup to resolve issue #179
+/// (files pulling need the parent folder to be already present)
+fn create_all_dirs(arbo: &Arbo, from: InodeId, mount_point: &WhPath) -> io::Result<()> {
+    let to_io_error = |_| {
+        io::Error::new(
+            io::ErrorKind::InvalidData,
+            "Arbo seems corrupted. Creation of the directory tree failed.",
+        )
+    };
+    let ignore_exists = |case: io::Result<()>| match case {
```
Comment (Arthur-Aillet) [inline src/pods/pod.rs:151]: Make it a private function

File: src/pods/pod.rs [hunk 4]
```diff
@@ -145,7 +208,7 @@ impl Pod {
     ) -> io::Result<Self> {
         let mut global_config = global_config;
 
-        log::info!("mount point {}", mount_point);
+        log::trace!("mount point {}", mount_point);
```
Comment (Arthur-Aillet) [inline src/pods/pod.rs:211]: 👍

**Review by Arthur-Aillet — CHANGES_REQUESTED** [review]

**Review by syborg64 — CHANGES_REQUESTED** [review]

File: src/pods/pod.rs [hunk 5]
```diff
@@ -134,6 +137,66 @@ custom_error! {pub PodStopError
...
+        .map_err(to_io_error)?;
+    ignore_exists(fs::create_dir(&mount_point.join(&current_path)))?;
+
+    for (path, perms, children) in directories {
+        let path = mount_point.join(&path);
+        ignore_exists(fs::create_dir(&path))?;
+        // REVIEW permissions are just reconverted from u16 to u32, as I've seen them
+        // be converted from u32 to u16 in fs_interface::setattr
+        // I'm not 100% sure that this is correct.
+        fs::set_permissions(&path, fs::Permissions::from_mode(perms as u32))?;
```
[the remark this answers is not in the document]
Comment (axel-denis) [reply src/pods/pod.rs:191]: aren't fs functions cross platform ?

[the remark this answers is not in the document]
Comment (syborg64) [reply src/pods/pod.rs:191]: no, since we use the filesystem differently based on the platform. beyond that, fs will call back INTO wormhole unexpectedly based on the loaded state of the pod. It's a perfect way to Infinite recursion.

Local storage MUST go through the local storage manager, that is how we designed this thing and we have to stick to it. we can't break our rules and invariants simply because it looks like it would work

**Comment by axel-denis** [comment]
Force merge (validated with @syborg64, @Arthur-Aillet and myself)
